version: "3"


services:
  devops1:
    build: devopshttp/
    restart: always
    ports:
      - 7782:80
    env_file:
    - variables.env    

  devops2:
    build: devopshttp/
    restart: always
    ports:
      - 7783:80
    env_file:
    - variables.env

  devops3:
    build: devopshttp/
    restart: always
    ports:
      - 7784:80
    environment:
      - DEVOPS="User"

  devops4:
    build: devopshttp/
    restart: always
    ports:
      - 7785:80
    env_file:
    - variables.env

  devops5:
    build: devopshttp/
    restart: always
    ports:
      - 7786:80
    env_file:
    - variables.env

  javaapp:
    build: javadocker/
    depends_on:
      - database
    restart: always
    ports:
      - 7787:80
    env_file:
    - variables.env

  database:
    build: databasedocker/
    
    restart: always
    ports:
      - 7788:80
    env_file:
    - variables.env
