#------Apache web-server running on Ubuntu--
#---------------Made by Alexey Krasichonak--
#-------------------------------------------

FROM openjdk:16-alpine3.13

WORKDIR /app

COPY .mvn/ .mvn
COPY mvnw pom.xml ./
RUN ./mvnw dependency:go-offline

COPY src ./src

CMD ["./mvnw", "spring-boot:run"]
