properties([disableConsurrentBuilds()])

pipeline {
    agent any
    stages {
        stage('Build docker image') {
            steps {
                dir ('Task6') {
                sh 'docker build . '
                    
                }
                
                '''
            }
        }
    }
}
