#!groovy

properties([disableConsurrentBuilds()])

pipeline {
    agent any
    stages {
        stage('Build docker image') {
            steps {
                cd ('Task6') {
                sh '''docker build . '''
                    
                }
                
                '''
            }
        }
    }
}
