---
- name: Install wordpress on docker
  hosts: all
  become: yes

  tasks:
  - name: Install required system packages
    apt:
        pkg:
            - python3-pip
            - ca-certificates
            - curl
            - gnupg
            - lsb-release
        state: latest
        update_cache: true

  - name: Install Docker Module for Python
    pip:
        name: docker

#  - name: Install Key
# #   shell: "sudo mkdir -p /etc/apt/keyrings ; curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg"
    
# # - name: Install Key 2
#    shell: 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null'

  - name: Install docker
    apt:
        pkg:
            - docker-ce
            - docker-ce-cli
            - containerd.io
            - docker-compose-plugin
        state: latest

  - name: Start docker service
    service: name=docker state=started enabled=yes


  - name: Run docker container
    community.docker.docker_container:
      name: mywordpress 
      image: wordpress

#  - name: Run docker contener
#    shell: "sudo docker run -d -p 8899:80 wordpress"
